# Combinatorics 

## Factorials

In [119]:
import math, scipy.special as sc, numpy as np

In [88]:
math.factorial(4), sc.factorial(4)

(24, 24.0)

## Permutation

In [89]:
math.perm(10,3), sc.perm(10,3)

(720, 720.0)

## Binomial Coefficients

In [90]:
math.comb(10,3), sc.comb(10,3), sc.binom(10,3)

(120, 120.0, 120.0)

## Counting

|   |Order matters   | matter  |
|---|---|---|
| with replacement  |product   |  combinations_with_replacement |
| without replacement  | permutations  |  combinations |


In [91]:
from itertools import product, permutations, combinations, combinations_with_replacement

### Order matters, with replacement

In [125]:
all_2_letters_words = list(product("ABC", repeat=2))
all_2_letters_words

[('A', 'A'),
 ('A', 'B'),
 ('A', 'C'),
 ('B', 'A'),
 ('B', 'B'),
 ('B', 'C'),
 ('C', 'A'),
 ('C', 'B'),
 ('C', 'C')]

In [93]:
print(len(all_2_letters_words))
assert len(all_2_letters_words) == 3 * 3 

9


### Order matters, without replacement

In [94]:
all_2_different_letters_words = list(permutations("ABC", 2))
all_2_different_letters_words

[('A', 'B'), ('A', 'C'), ('B', 'A'), ('B', 'C'), ('C', 'A'), ('C', 'B')]

In [95]:
print(len(all_2_different_letters_words))
assert len(all_2_different_letters_words) == math.perm(3,2)

6


### Order doesn't matter, without replacement: n choose k

In [96]:
nCk = list(combinations("ABC", 2))
nCk

[('A', 'B'), ('A', 'C'), ('B', 'C')]

In [97]:
print(len(nCk))
assert len(nCk) == math.comb(3,2)

3


### Order doesn't matter, with replacement: Bose-Einstein

In [100]:
be = list(combinations_with_replacement("ABC", 2))
be 

[('A', 'A'), ('A', 'B'), ('A', 'C'), ('B', 'B'), ('B', 'C'), ('C', 'C')]

In [101]:
len(be)

6

# Sampling

In [115]:
# R: sample(x, size, replace = FALSE, prob = NULL)

## python.random

In [104]:
from random import choice, choices, sample

In [126]:
choice(['A', 'B', 'C']) 

'B'

In [112]:
choices(['A', 'B', 'C'], k=2) # with replacement

['C', 'C']

In [114]:
sample(['A', 'B', 'C'], k=2)  # without replacement

['A', 'B']

## numpy.random

In [138]:
# random.choice(a, size=None, replace=True, p=None)

In [136]:
np.random.choice(3,2)

array([1, 2])

### example: de Montmort's matching problem

In [264]:
n = 1000
N = 10 ** 5

numbers = [i for i in range(1, n + 1)]
res = []

for i in range(N):
    a = sum(np.random.choice(numbers, n, replace = False) == numbers)
    res.append(a)
    
sum(np.array(res) >=1) / N

0.63397

In [263]:
1 - 1 / math.e

0.6321205588285577

### Bexample: Birthday 

In [272]:
n = 10
N = 5
numbers = [i for i in range(1, n + 1)]
np.random.choice(numbers, n*N, replace = True).reshape(N, n)

array([[ 7,  9, 10,  4, 10,  5,  1,  1,  7, 10],
       [ 5,  1,  5,  5,  1,  2, 10,  1, 10,  6],
       [ 3,  6, 10, 10,  5,  8,  1,  3,  3,  5],
       [ 4,  6,  2,  5,  5,  4,  2,  2,  9,  6],
       [10,  6,  6,  1,  9,  9,  7,  7,  2,  3]])

In [280]:
from random import randint
 
 
NUM_PEOPLE = 23
NUM_POSSIBLE_BIRTHDAYS = 365
NUM_TRIALS = 10000
 
 
def generate_random_birthday():
    birthday = randint(1, NUM_POSSIBLE_BIRTHDAYS)
    return birthday
 
 
def generate_k_birthdays(k):
    birthdays = [generate_random_birthday() for _ in range(k)]
    return birthdays
 
 
def aloc(birthdays):
    unique_birthdays = set(birthdays)
 
    num_birthdays = len(birthdays)
    num_unique_birthdays = len(unique_birthdays)
    has_coincidence = (num_birthdays != num_unique_birthdays)
 
    return has_coincidence
 
 
def estimate_p_aloc():
    num_aloc = 0
    for _ in range(NUM_TRIALS):
        birthdays = generate_k_birthdays(NUM_PEOPLE)
        has_coincidence = aloc(birthdays)
        if has_coincidence:
            num_aloc += 1
 
    p_aloc = num_aloc / NUM_TRIALS
    return p_aloc
 
 
p_aloc = estimate_p_aloc()
print(f"Estimated P(ALOC) after {NUM_TRIALS} trials: {p_aloc}")

Estimated P(ALOC) after 10000 trials: 0.5072


In [289]:
days = [i for i in range(1, 366)]
people = 23

def birthday_sim(people):
    sims, unique_birthdays = 2000, 0 
    for _ in range(sims):
        draw = np.random.choice(days, size=people, replace=True)
        if len(draw) == len(set(draw)): 
            unique_birthdays += 1
    out = 1 - unique_birthdays / sims
    return out

birthday_sim(people)

0.499

0.514

## scikit-learn

In [117]:
from sklearn.utils import resample

In [290]:
resample(np.arange(1,10), n_samples=10, replace=True,random_state=2)

array([9, 9, 7, 3, 9, 8, 3, 2, 6, 5])

## pandas

In [121]:
import pandas as pd
df = pd.DataFrame({'a': [1, 2, 3, 4, 5], 'b': [6, 7, 8, 9, 0]})
df

a  b
0  1  6
1  2  7
2  3  8
3  4  9
4  5  0

In [122]:
df.sample(3)

a  b
0  1  6
3  4  9
2  3  8

In [123]:
 df['a'].sample(4, replace=True, weights=df['b'])

0    1
2    3
0    1
1    2
Name: a, dtype: int64

# Random Numbers